Add rule namespace:meter_pvc_bytes_total:sum
kubesphere/ks-installer pull request #1165
Opened 2020-11-26 06:20 UTC by yunkunrao

2020-11-26 12:50 UTC, benjaminhuo commented on roles/ks-monitor/files/prometheus/prometheus-rules-v1.16+.yaml
> +        max by (namespace, node, persistentvolumeclaim) (kubelet_volume_stats_capacity_bytes) * on (namespace, persistentvolumeclaim) group_left (storageclass) kube_persistentvolumeclaim_info{} * on(
kube_persistentvolumeclaim_info{} 
=>
kube_persistentvolumeclaim_info{job="kube-state-metrics"}

2020-11-26 12:56 UTC, benjaminhuo commented on roles/ks-monitor/files/prometheus/prometheus-rules-v1.16+.yaml
> +      record: namespace:meter_pvc_bytes_total:sum
namespace:meter_pvc_bytes_total:sum
=>
namespace:pvc_bytes_total:

2020-11-26 12:57 UTC, benjaminhuo requested changes
Pls see my comments above

2020-11-28 14:03 UTC, yunkunrao commented on roles/ks-monitor/files/prometheus/prometheus-rules-v1.16+.yaml
> +        max by (namespace, node, persistentvolumeclaim) (kubelet_volume_stats_capacity_bytes) * on (namespace, persistentvolumeclaim) group_left (storageclass) kube_persistentvolumeclaim_info{} * on(
got it

2020-11-28 14:03 UTC, yunkunrao commented on roles/ks-monitor/files/prometheus/prometheus-rules-v1.16+.yaml
> +      record: namespace:meter_pvc_bytes_total:sum
got it

2020-11-29 03:09 UTC, benjaminhuo approved these changes

2020-11-29 03:09 UTC, benjaminhuo commented
/lgtm

2020-11-29 14:43 UTC, pixiake commented
/approve

2020-11-29 14:44 UTC, merged