add nginx ingress prometheus config
kubesphere/ks-installer pull request #1205
Opened 2020-12-20 13:47 UTC by zackzhangkai

add nginx ingress prometheus config

Signed-off-by: zackzhangkai <zackzhang@yunify.com>

2020-12-20 13:48 UTC, zackzhangkai commented
/assign @pixiake
/cc @zryfish

2020-12-20 13:53 UTC, zackzhangkai commented
/cc @benjaminhuo

2020-12-21 02:12 UTC, benjaminhuo requested changes

2020-12-21 02:12 UTC, benjaminhuo commented on roles/ks-istio/files/prometheus/prometheus-additional.yaml
>  # Mixer scrapping. Defaults to Prometheus and mixer on same namespace.
The additional Prometheus config is stored in https://github.com/kubesphere/ks-installer/blob/344e2da1add10e1d7436ec6e83dee680b72b8cd6/roles/ks-monitor/files/prometheus/prometheus/additional-scrape-configs.yaml , Just wondering why adding this file?

2020-12-21 02:12 UTC, benjaminhuo commented on roles/ks-istio/files/prometheus/prometheus-additional.yaml
> +  scrape_interval: 1m
The scrape interval has been changed to 15s on purpose since 2.0, so we needn't change it back to 1m

2020-12-21 03:12 UTC, zackzhangkai commented on roles/ks-istio/files/prometheus/prometheus-additional.yaml
>  # Mixer scrapping. Defaults to Prometheus and mixer on same namespace.
@benjaminhuo  This file will be used when install or upgrade.

2020-12-21 03:16 UTC, zackzhangkai commented on roles/ks-istio/files/prometheus/prometheus-additional.yaml
> +  scrape_interval: 1m
@benjaminhuo To release the burden of the system, these scrapes which are not sensitive are changed to 1m on purpose. Others, such as the envoy and ingress are still 15s.

2020-12-21 03:17 UTC, benjaminhuo commented on roles/ks-istio/files/prometheus/prometheus-additional.yaml
>  # Mixer scrapping. Defaults to Prometheus and mixer on same namespace.
where to install?
these scrape configs will be pickup by prometheus operator only if it's put in additional-scrape-configs.yaml  secret.

2020-12-21 03:32 UTC, zackzhangkai commented on roles/ks-istio/files/prometheus/prometheus-additional.yaml
>  # Mixer scrapping. Defaults to Prometheus and mixer on same namespace.
https://github.com/kubesphere/ks-installer/blob/c872a205426be680664057a18828cea91f5650e7/roles/ks-istio/tasks/main.yaml#L89

2020-12-21 05:23 UTC, benjaminhuo commented on roles/ks-istio/files/prometheus/prometheus-additional.yaml
>  # Mixer scrapping. Defaults to Prometheus and mixer on same namespace.
it's better to change this file together with roles/ks-monitor/files/prometheus/prometheus/additional-scrape-configs.yaml , we cannot ensure which files will be applied first

2020-12-21 05:54 UTC, zackzhangkai commented on roles/ks-istio/files/prometheus/prometheus-additional.yaml
>  # Mixer scrapping. Defaults to Prometheus and mixer on same namespace.
I think there is no need to maintain two configurations, which are the same indeed. Maybe we can delete the configuration in roles/ks-monitor/files/prometheus/prometheus/additional-scrape-configs.yaml, together with the file https://github.com/kubesphere/kube-prometheus/blob/ks-v3.0/manifests/additional-scrape-configs.yaml

2020-12-21 06:51 UTC, benjaminhuo commented on roles/ks-istio/files/prometheus/prometheus-additional.yaml
>  # Mixer scrapping. Defaults to Prometheus and mixer on same namespace.
No, istio is an optional component and you've put non-istio scrape config in ks-installer/roles/ks-istio/tasks/main.yaml, so if istio is not installed and you delete roles/ks-monitor/files/prometheus/prometheus/additional-scrape-configs.yaml , nginx ingress metrics will not be collected

https://github.com/kubesphere/kube-prometheus/ is kubesphere's customization to upstream project, it has nothing to do with installer.

2020-12-21 07:11 UTC, zackzhangkai commented on roles/ks-istio/files/prometheus/prometheus-additional.yaml
>  # Mixer scrapping. Defaults to Prometheus and mixer on same namespace.
Maybe split out the nginx scrape conf from this file is better. To add an another nginx scrape config ,such  as the additional-scrape-configs.yaml, or transfer the nginx scrape config to podmonitor. What do you think about this?

2020-12-21 07:18 UTC, benjaminhuo commented on roles/ks-istio/files/prometheus/prometheus-additional.yaml
>  # Mixer scrapping. Defaults to Prometheus and mixer on same namespace.
It's not necessary to make it over complicated. why not just remove `roles/ks-istio/files/prometheus/prometheus-additional.yaml` and keep `roles/ks-monitor/files/prometheus/prometheus/additional-scrape-configs.yaml` ?

2020-12-21 15:01 UTC, zackzhangkai commented on roles/ks-istio/files/prometheus/prometheus-additional.yaml
>  # Mixer scrapping. Defaults to Prometheus and mixer on same namespace.
Because we can not determine which module would be executed earlier, so both of them need to be modified. I had modified. Please review again.

2020-12-22 02:17 UTC, benjaminhuo commented on roles/ks-istio/files/prometheus/prometheus-additional.yaml
>  # Mixer scrapping. Defaults to Prometheus and mixer on same namespace.
The content of `roles/ks-istio/files/prometheus/additional-scrape-configs.yaml` and `roles/ks-monitor/files/prometheus/prometheus/additional-scrape-configs.yaml` are exactly the same, just keep one copy of these 2 is ok. `roles/ks-monitor/files/prometheus/prometheus/additional-scrape-configs.yaml` should be kept.

`roles/ks-istio/files/prometheus/prometheus-additional.yaml` is also necessary because it's plain text (not base64 encoded content) and is more friendly to reviewers.

So I think we can keep just `roles/ks-monitor/files/prometheus/prometheus/additional-scrape-configs.yaml` and `roles/ks-istio/files/prometheus/prometheus-additional.yaml`

2020-12-22 05:42 UTC, zackzhangkai commented on roles/ks-istio/files/prometheus/prometheus-additional.yaml
> +  scrape_interval: 1m
@benjaminhuo  Done

2020-12-22 05:53 UTC, benjaminhuo approved these changes
/lgtm

2020-12-22 06:13 UTC, pixiake commented
/approve

2020-12-22 06:14 UTC, merged