integration of custom alerting
kubesphere/ks-installer pull request #1249
Opened 2021-02-01 06:56 UTC by junotx

2021-02-01 08:07 UTC, benjaminhuo requested changes

2021-02-02 03:40 UTC, benjaminhuo commented
/assign @pixiake

2021-02-02 03:44 UTC, benjaminhuo commented on roles/ks-monitor/files/prometheus/thanosruler/thanosruler.yaml
> +  image: quay.io/thanos/thanos:v0.18.0
It better to be the image from the dockerhub repo here too: `thanosio/thanos`

2021-02-02 08:32 UTC, pixiake commented on roles/ks-monitor/files/prometheus/thanosruler/thanosruler.yaml
> +  image: quay.io/thanos/thanos:v0.18.0
Image name is better as a parameter in https://github.com/kubesphere/ks-installer/blob/master/roles/download/defaults/main.yml

2021-02-03 02:50 UTC, pixiake commented
/lgtm
/approve

2021-02-03 02:50 UTC, merged