Upgrade nginx ingress controller version
kubesphere/ks-installer pull request #1253
Opened 2021-02-05 05:26 UTC by wenhuwang

Signed-off-by: wang_wenhu <976400757@qq.com>

**What type of PR is this?**
> /kind optimization

**Which issue(s) this PR fixes**:

Fixes #1252

2021-02-05 05:29 UTC, wenhuwang commented
/assign @rayzhou2017

2021-02-18 02:05 UTC, LinuxSuRen requested changes
Thanks for your contribution. But I cannot find the image that you try to upgrade to.

```
[root@i-credeh69 ~]# docker pull kubesphere/nginx-ingress-controller:v0.44.0
Error response from daemon: manifest for kubesphere/nginx-ingress-controller:v0.44.0 not found: manifest unknown: manifest unknown

[root@i-credeh69 ~]# docker pull kubesphere/nginx-ingress-controller:0.44.0
Error response from daemon: manifest for kubesphere/nginx-ingress-controller:0.44.0 not found: manifest unknown: manifest unknown
```

Normally we should be careful about the upgrading. I know you must have some reasons why you want to upgrade it. In order to make all others can help to review if it's ok to upgrade, please list the reasons.

Or you even can list the potential problems after upgrading it.

2021-02-18 02:09 UTC, LinuxSuRen commented
/kind cleanup

2021-02-18 03:55 UTC, zackzhangkai commented on roles/ks-core/ks-core/templates/ingress-controller.yaml.j2
> -            - --force-namespace-isolation
Why do you remove this parameter? Ingress controller is isolated for different namespaces in KubeSphere.

2021-02-19 02:42 UTC, wenhuwang commented on roles/ks-core/ks-core/templates/ingress-controller.yaml.j2
> -            - --force-namespace-isolation
"Flag --force-namespace-isolation is deprecated and will be removed in 0.24. Currently this annotation is being replaced by --watch-namespace. " ,this  words come from  [ingress-nginx change log](https://github.com/kubernetes/ingress-nginx/blob/master/Changelog.md).

2021-02-19 03:05 UTC, wenhuwang commented
> Thanks for your contribution. But I cannot find the image that you try to upgrade to.
> 
> ```
> [root@i-credeh69 ~]# docker pull kubesphere/nginx-ingress-controller:v0.44.0
> Error response from daemon: manifest for kubesphere/nginx-ingress-controller:v0.44.0 not found: manifest unknown: manifest unknown
> 
> [root@i-credeh69 ~]# docker pull kubesphere/nginx-ingress-controller:0.44.0
> Error response from daemon: manifest for kubesphere/nginx-ingress-controller:0.44.0 not found: manifest unknown: manifest unknown
> ```
> 
> Normally we should be careful about the upgrading. I know you must have some reasons why you want to upgrade it. In order to make all others can help to review if it's ok to upgrade, please list the reasons.
> 
> Or you even can list the potential problems after upgrading it.

1. I'm afraid i don't have permission to push the image `kubesphere/nginx-ingress-controller:v0.44.0`;
2. We have encountered some bugs in the configuration of https certificate in the process of using nginx-ingress. The later version of nginx-ingress has been fixed. There may be many similar bugs, so I suggest to upgrade the version appropriately. We can discuss the specific version.

2021-02-19 03:14 UTC, LinuxSuRen commented
hi @sig-infra, do we have any instructions about where the image `kubesphere/nginx-ingress-controller` comes from, how to upgrade it. I believe that @wenhuwang would like to help to maintain it if we have the relevant documents.

2021-03-01 09:03 UTC, zryfish commented on roles/ks-core/ks-core/templates/ingress-controller.yaml.j2
> -            - --force-namespace-isolation
Definitely agree we should upgrade the ingress controller, but since v0.44 is way newer than 0.22, I was wondering is this going to introduce any break changes to current users?

2021-03-01 09:19 UTC, wenhuwang commented on roles/ks-core/ks-core/templates/ingress-controller.yaml.j2
> -            - --force-namespace-isolation
After the upgrade, only the new ingress will use the new version。

2021-03-02 12:59 UTC, zackzhangkai commented
/deploy

2021-03-02 13:05 UTC, zackzhangkai commented
/deploy

2021-03-02 13:13 UTC, zackzhangkai commented
/deploy

2021-03-03 02:08 UTC, zackzhangkai commented
/deploy

2021-03-03 02:49 UTC, zackzhangkai commented
/deploy

2021-03-03 03:11 UTC, zackzhangkai commented
/deploy

2021-03-03 03:50 UTC, zackzhangkai commented
/deploy

2021-03-04 08:02 UTC, zackzhangkai commented
@wenhuwang  please rebase master firstly, then we will test your PR with comment.

2021-03-10 03:04 UTC, zackzhangkai commented
/deploy

2021-03-10 08:22 UTC, zackzhangkai commented
/deploy

2021-03-10 08:45 UTC, zackzhangkai commented
/deploy

2021-03-10 13:41 UTC, zackzhangkai commented
/lgtm

2021-03-11 02:29 UTC, pixiake commented
/approve

2021-03-11 02:30 UTC, merged