Unify the name in [k8s / kubernetes] and [storage class / StorageClass]  …
kubesphere/ks-installer pull request #1255
Opened 2021-02-08 06:32 UTC by daniel-hutao

Unify the name in [k8s / kubernetes] and [storage class / StorageClass]  …

Signed-off-by: daniel-hutao <farmer.hutao@outlook.com>

2021-02-18 01:51 UTC, Forest-L commented
/lgtm

2021-02-18 01:52 UTC, Forest-L commented
/approve

2021-02-18 01:53 UTC, merged

2021-02-18 01:54 UTC, LinuxSuRen requested changes

2021-02-18 01:54 UTC, LinuxSuRen commented on roles/ks-core/config/tasks/main.yaml
> +- name: KubeSphere | Checking kubernetes version
`kubernetes`

Please capitalize the first letter.

2021-02-18 01:54 UTC, LinuxSuRen commented on roles/ks-core/config/tasks/main.yaml
> +    msg: Current kubernetes version is {{kubernetes_version.stdout}}
`kubernetes`

Please capitalize the first letter.

Kubernetes or KubeSphere are all special word instead the normal one.

2021-02-18 01:54 UTC, LinuxSuRen commented on roles/ks-core/ks-core/tasks/main.yaml
> +- name: KubeSphere | Import ks-core status
Why don't use `importing` here?

2021-02-18 02:07 UTC, daniel-hutao commented on roles/ks-core/ks-core/tasks/main.yaml
> +- name: KubeSphere | Import ks-core status
If it is needed, I would do change it to importing later.

2021-02-20 06:48 UTC, daniel-hutao commented on roles/ks-core/config/tasks/main.yaml
> +- name: KubeSphere | Checking kubernetes version
#1256

2021-02-20 06:49 UTC, daniel-hutao commented on roles/ks-core/config/tasks/main.yaml
> +    msg: Current kubernetes version is {{kubernetes_version.stdout}}
#1256

2021-02-20 06:49 UTC, daniel-hutao commented on roles/ks-core/ks-core/tasks/main.yaml
> +- name: KubeSphere | Import ks-core status
#1256