Let ks-installer support optional configuration with authentication a…
kubesphere/ks-installer pull request #1333
Opened 2021-03-19 09:31 UTC by daniel-hutao

Let ks-installer support optional configuration with authentication and non-authentication es clusters;

Signed-off-by: daniel-hutao <farmer.hutao@outlook.com>

kubesphere/kubesphere/issues/3457 step1

fluent-bit support

2021-03-19 09:33 UTC, daniel-hutao commented
@benjaminhuo

2021-03-19 10:59 UTC, benjaminhuo requested changes

2021-03-19 11:13 UTC, benjaminhuo commented
For the es jaeger uses @zackzhangkai will tell you how to set username/password

2021-03-19 13:25 UTC, benjaminhuo commented on roles/ks-logging/templates/custom-output-elasticsearch-logging.yaml.j2
> +{% if common.es.basicAuth.enabled is defined and common.es.basicAuth.enabled is true %}
the condition below is the same for both httpUser and httpPassword, so just one if-endif is enough for both username and password:

`{% if common.es.basicAuth.enabled is defined and common.es.basicAuth.enabled is true %}`

2021-03-19 13:25 UTC, benjaminhuo requested changes
See my comments above

2021-03-20 03:12 UTC, zackzhangkai commented
@daniel-hutao Please refer to this doc https://www.jaegertracing.io/docs/1.21/operator/#external-elasticsearch to add a secret to es. Such as

```bash
apiVersion: jaegertracing.io/v1
kind: Jaeger
metadata:
  name: simple-prod
spec:
  strategy: production
  storage:
    type: elasticsearch # <1>
    options:
      es:
        server-urls: https://quickstart-es-http.default.svc:9200 # <2>
        index-prefix: my-prefix
        tls: # <3>
          ca: /es/certificates/ca.crt
    secretName: jaeger-secret # <4>
```

 Secret which defines environment variables ES_PASSWORD and ES_USERNAME. Created by `kubectl create secret generic jaeger-secret --from-literal=ES_PASSWORD=changeme --from-literal=ES_USERNAME=elastic`

2021-03-20 03:16 UTC, zackzhangkai commented on deploy/cluster-configuration.yaml
> +        password: ""
plaintext password is not a good way, I think.

2021-03-21 12:52 UTC, benjaminhuo commented on deploy/cluster-configuration.yaml
> +        password: ""
It's ok for now to put username/password in cluster-configuration, @pixiake could reflector this later maybe.

2021-03-21 12:59 UTC, benjaminhuo commented
> @daniel-hutao Please refer to this doc https://www.jaegertracing.io/docs/1.21/operator/#external-elasticsearch to add a secret to es. Such as
> 
> ```shell
> apiVersion: jaegertracing.io/v1
> kind: Jaeger
> metadata:
>   name: simple-prod
> spec:
>   strategy: production
>   storage:
>     type: elasticsearch # <1>
>     options:
>       es:
>         server-urls: https://quickstart-es-http.default.svc:9200 # <2>
>         index-prefix: my-prefix
>         tls: # <3>
>           ca: /es/certificates/ca.crt
>     secretName: jaeger-secret # <4>
> ```
> 
> Secret which defines environment variables ES_PASSWORD and ES_USERNAME. Created by `kubectl create secret generic jaeger-secret --from-literal=ES_PASSWORD=changeme --from-literal=ES_USERNAME=elastic`

Thanks zack , KubeSphere's jaeger config could be found [here](https://github.com/kubesphere/ks-installer/blob/master/roles/ks-istio/templates/jaeger-cr.yaml.j2#L21)

2021-03-21 14:28 UTC, daniel-hutao commented on roles/ks-logging/templates/custom-output-elasticsearch-logging.yaml.j2
> +{% if common.es.basicAuth.enabled is defined and common.es.basicAuth.enabled is true %}
right

2021-03-21 14:29 UTC, daniel-hutao commented
@benjaminhuo @zackzhangkai I'll do it tomorrow. Thank you for your tips.

2021-03-22 01:57 UTC, daniel-hutao commented on roles/ks-istio/tasks/jaeger-install.yaml
> +- name: servicemesh | Deploying jaeger-secret
I'm not sure if this modification method is optimal

2021-03-22 02:40 UTC, benjaminhuo requested changes

2021-03-22 02:40 UTC, benjaminhuo commented on roles/ks-istio/tasks/jaeger-install.yaml
> +  shell: "{{ bin_dir }}/kubectl create secret generic jaeger-secret --from-literal=ES_PASSWORD={{ common.es.basicAuth.username }} --from-literal=ES_USERNAME={{ common.es.basicAuth.password }} --names
looks like the password and username are mixed up:
```yaml
--from-literal=ES_PASSWORD={{ common.es.basicAuth.username }} 
--from-literal=ES_USERNAME={{ common.es.basicAuth.password }}
```

2021-03-22 02:40 UTC, benjaminhuo commented on roles/ks-istio/tasks/jaeger-install.yaml
> +    - "common.es.basicAuth == true"
You mean ?
```yaml
  when:
    - common.es.basicAuth.enabled is defined
    - common.es.basicAuth.enabled == true
```
Usually the when clause looks like [here](https://github.com/kubesphere/ks-installer/blob/master/roles/ks-monitor/tasks/etcd.yaml#L11):
```yaml
  when:
    - etcd.monitoring is defined
    - etcd.monitoring == true
```

2021-03-22 02:54 UTC, daniel-hutao reviewed
I've coded it

2021-03-22 02:57 UTC, daniel-hutao commented on roles/ks-istio/tasks/jaeger-install.yaml
> +    - "common.es.basicAuth == true"
I was careless

2021-03-22 02:57 UTC, daniel-hutao commented on roles/ks-istio/tasks/jaeger-install.yaml
> +    - "common.es.basicAuth == true"
大意了

2021-03-22 03:37 UTC, benjaminhuo commented
@pixiake is there anything else to change except `deploy/cluster-configuration.yaml` to add es basicAuth option？ These new added options will be generated to kubesphere-config cm?

2021-03-22 05:10 UTC, zackzhangkai commented
you can use '/deploy' to create a cluster, and then to test if your pr is ok.

2021-03-22 05:10 UTC, zackzhangkai commented
/deploy

2021-03-22 05:52 UTC, zackzhangkai commented
@daniel-hutao http://139.198.120.40:30880/login  you can check if your pr is ok. I found the configuration is not the same as expected.

```bash
# kubectl get cc -n kubesphere-system -oyaml | grep -i secret | grep -v jwt
[root@tf-cd-allinone-0 ~]#
```

2021-03-22 06:03 UTC, daniel-hutao commented
> @daniel-hutao http://139.198.120.40:30880/login you can check if your pr is ok. I found the configuration is not the same as expected.
> 
> ```shell
> # kubectl get cc -n kubesphere-system -oyaml | grep -i secret | grep -v jwt
> [root@tf-cd-allinone-0 ~]#
> ```

My PC cannot access the http site due to company security policy restrictions.

2021-03-22 07:45 UTC, zackzhangkai commented
Cannot ssh to the host

2021-03-22 08:10 UTC, daniel-hutao commented
> Cannot ssh to the host

So I have no way to verify this way，，，

2021-03-23 01:44 UTC, zackzhangkai commented
@daniel-hutao  By the way, how do you test your PR?  If you install KS via your PR, then you can find what I met with.

2021-03-23 01:59 UTC, daniel-hutao commented
> @daniel-hutao By the way, how do you test your PR? If you install KS via your PR, then you can find what I met with.

I'll build ks-installer image to test it later

2021-03-23 03:12 UTC, benjaminhuo approved these changes
/lgtm

2021-03-23 03:14 UTC, benjaminhuo commented
> @pixiake is there anything else to change except `deploy/cluster-configuration.yaml` to add es basicAuth option？ These newly added options will be generated to kubesphere-config cm?

@pixiake pls take a look at this PR

2021-03-25 13:27 UTC, zackzhangkai commented
/lgtm

2021-03-26 06:03 UTC, pixiake commented
/approve

2021-03-26 06:04 UTC, merged