Fix prometheus-operator cannot list resource probes error
kubesphere/ks-installer pull request #1419
Opened 2021-04-19 01:56 UTC by daniel-hutao

Signed-off-by: Daniel Hu <farmer.hutao@outlook.com>

Fixes #kubesphere/issues/3759

2021-04-19 01:58 UTC, daniel-hutao commented
![image](https://user-images.githubusercontent.com/18692628/115171500-b8a22d80-a0f5-11eb-8431-1fb09fe7a07c.png)

2021-04-19 08:20 UTC, benjaminhuo commented on roles/ks-monitor/files/prometheus/init/prometheus-operator-clusterRole.yaml
> +  - probes
Thanks for the PR,
Pls also add probes as below:

```shell
- apiGroups:
  - apiextensions.k8s.io
  resourceNames:
...
  - probes.monitoring.coreos.com
```

2021-04-19 08:21 UTC, benjaminhuo requested changes
See my comments above

2021-04-19 08:38 UTC, daniel-hutao commented
/need-to-verify

I'll check it again by deploy the latest ks version tonight.

2021-04-19 11:26 UTC, daniel-hutao commented on roles/ks-monitor/files/prometheus/init/prometheus-operator-clusterRole.yaml
> +  - probes
Ok

2021-04-19 11:34 UTC, benjaminhuo commented
You can `git commit -s --amend` and then `git push -f`  to attach modification to the original commit , then run `git fetch upstream` and `git rebase upstream/master` to rebase the upstream changes to make the PR commits clean

2021-04-19 11:36 UTC, benjaminhuo commented
/lgtm
/assign @pixiake

2021-04-19 11:36 UTC, benjaminhuo approved these changes

2021-04-19 11:42 UTC, benjaminhuo commented
/lgtm

2021-04-19 11:45 UTC, daniel-hutao commented
> You can `git commit -s --amend` and then `git push -f` to attach modification to the original commit, then run `git fetch upstream` and `git rebase upstream/master` to rebase the upstream changes to make the PR commits clean in the future @daniel-hutao

Thanks for reminding, I just adjusted the pr and it's suitable now.

2021-04-19 11:48 UTC, benjaminhuo commented
> > You can `git commit -s --amend` and then `git push -f` to attach modification to the original commit, then run `git fetch upstream` and `git rebase upstream/master` to rebase the upstream changes to make the PR commits clean in the future @daniel-hutao
> 
> Thanks for reminding, I just adjusted the pr and it's suitable now.

Great!

2021-04-20 01:07 UTC, zryfish commented
/approve

2021-04-20 01:08 UTC, merged