Add service monitor for jenkins
kubesphere/ks-installer pull request #1490
Opened 2021-04-28 09:40 UTC by JohnNiang

Add service monitor resource for jenkins prometheus endpoint. Please follow up <https://github.com/kubesphere/kubesphere/issues/3814>.

2021-05-24 02:22 UTC, JohnNiang commented
/cc @kubesphere/sig-observability

2021-05-24 02:31 UTC, benjaminhuo commented
@junotx Please help to review this

2021-05-24 02:42 UTC, LinuxSuRen requested changes
I left some comments. Please take a look at it.

2021-05-24 02:42 UTC, LinuxSuRen commented on roles/ks-monitor/files/prometheus/devops/prometheus-serviceMonitorJenkins.yaml
> +    - kubesphere-devops-system
How to monitor the namespace `kubesphere-devops-worker`?

2021-05-24 03:05 UTC, JohnNiang commented on roles/ks-devops/jenkins/defaults/main.yaml
> -Java_Opts: -Xms3g -Xmx6g -XX:MaxRAM=8g -Dhudson.slaves.NodeProvisioner.initialDelay=20  -Dhudson.slaves.NodeProvisioner.MARGIN=50 -Dhudson.slaves.NodeProvisioner.MARGIN0=0.85 -Dhudson.model.LoadStati
I'll revert this unrelated change and put them into another pr.

2021-05-24 03:06 UTC, JohnNiang commented on roles/ks-devops/jenkins/defaults/main.yaml
> -Java_Opts: -Xms3g -Xmx6g -XX:MaxRAM=8g -Dhudson.slaves.NodeProvisioner.initialDelay=20  -Dhudson.slaves.NodeProvisioner.MARGIN=50 -Dhudson.slaves.NodeProvisioner.MARGIN0=0.85 -Dhudson.model.LoadStati
Because this variable is not used by anywhere.

2021-05-24 03:11 UTC, JohnNiang commented on roles/ks-devops/jenkins/templates/worker-resourcequota.yaml.j2
> +    limits.memory: 38Gi
Alright.

2021-05-24 09:42 UTC, JohnNiang commented on roles/ks-monitor/files/prometheus/devops/prometheus-serviceMonitorJenkins.yaml
> +    - kubesphere-devops-system
There is no need to monitor namespace `kubesphere-devops-worker`. BTY, this ServiceMonitor is only for ks-jenkins which namespace is `kubesphere-devops-system`.

2021-05-24 09:42 UTC, JohnNiang commented on roles/ks-monitor/files/prometheus/devops/prometheus-devopsAlertRules.yaml
> +            severity: warning
Alright.

2021-05-24 10:04 UTC, JohnNiang commented
/hold

2021-05-24 10:04 UTC, JohnNiang commented
/unhold

2021-05-24 10:19 UTC, LinuxSuRen commented
Please don't forget check the ci status once your PR is ready.

2021-05-24 10:21 UTC, LinuxSuRen commented
By the way, consider there're a lot of commits in this PR. Please consider the following steps (or more better ideas):

* squash your commits into one
* make this merge method to be `squash` by filing a PR to [prow](https://github.com/kubesphere/prow-tutorial/blob/master/ks-ci-bot/config.yaml#L19)

2021-05-24 10:24 UTC, LinuxSuRen commented
I'd suggest that you create an issue to file the below information instead of just comment here. Because it's quite important for the users, we need to document it officially.

![image](https://user-images.githubusercontent.com/1450685/119334000-2c1ef800-bcbd-11eb-98c8-7d9be9973c55.png)

2021-05-24 10:40 UTC, JohnNiang commented
> By the way, consider there're a lot of commits in this PR. Please consider the following steps (or more better ideas):
> 
> * squash your commits into one
> * make this merge method to be `squash` by filing a PR to [prow](https://github.com/kubesphere/prow-tutorial/blob/master/ks-ci-bot/config.yaml#L19)

Done.

2021-05-24 10:44 UTC, LinuxSuRen commented on roles/ks-devops/jenkins/defaults/main.yaml
> -Java_Opts: -Xms3g -Xmx6g -XX:MaxRAM=8g -Dhudson.slaves.NodeProvisioner.initialDelay=20  -Dhudson.slaves.NodeProvisioner.MARGIN=50 -Dhudson.slaves.NodeProvisioner.MARGIN0=0.85 -Dhudson.model.LoadStati
Got you.

2021-05-24 10:47 UTC, LinuxSuRen requested changes
There're many references to `kubesphere-devops-system`. Please check all of them, make sure we don't have compatible issues exist.

![image](https://user-images.githubusercontent.com/1450685/119336610-70f85e00-bcc0-11eb-885c-f6853840cdc8.png)

2021-05-25 09:05 UTC, junotx commented on roles/ks-monitor/files/prometheus/devops/prometheus-devopsAlertRules.yaml
> +        - alert: JenkinsCPUOvercommit
Please follow the [k8s resources naming rule](https://kubernetes.io/zh/docs/concepts/overview/working-with-objects/names/#names) to name alerting rules when configure custom alerting rules (which will be loaded by thanos ruler component), or configure them as builtin alerting rules (which will be loaded by prometheus component and cannot be updated by console)

2021-05-25 09:09 UTC, JohnNiang commented on roles/ks-monitor/files/prometheus/devops/prometheus-devopsAlertRules.yaml
> +        - alert: JenkinsCPUOvercommit
Thank you for reminding me. I'll correct them by following the naming rule.

2021-05-25 10:45 UTC, JohnNiang commented
@LinuxSuRen I've added two issues (<https://github.com/kubesphere/website/issues/1616>, https://github.com/kubesphere/website/issues/1617) into website repo, please have a look at them.

2021-05-25 11:39 UTC, LinuxSuRen requested changes

2021-05-25 11:39 UTC, LinuxSuRen commented on docs/JenkinsUpgradeGuide.md
>  upgrade [Kubesphere Jenkins](https://github.com/kubesphere/ks-jenkins).
It is impossible to upgrade any version to the target version.. Please add a declaration. Such as

![image](https://user-images.githubusercontent.com/1450685/119487515-1298b180-bd8c-11eb-8cd1-a089715ebcd4.png)

See also https://www.jenkins.io/doc/upgrade-guide/2.277/

2021-05-25 11:39 UTC, LinuxSuRen commented on docs/JenkinsUpgradeGuide.md
> +## Upgrade to v3.1.1
Please add a notice that v3.1.1 is not released yet.

2021-05-25 11:39 UTC, LinuxSuRen commented on roles/ks-monitor/files/prometheus/devops/prometheus-devopsAlertRules.yaml
> +            summary: Too many failed jobs.
It's unclear. What is the condition of it. For example: how long does it last?

2021-05-25 14:16 UTC, LinuxSuRen approved these changes
/lgtm

2021-05-26 08:36 UTC, JohnNiang commented
/hold

2021-05-26 15:59 UTC, JohnNiang commented
I've remove `jenkins-cpu-overcommit` rule for uncertain statistic and `jenkins-inodes-filling-up` rule for repeat alert in buitin alert rule `NodeFilesystemFilesFillingUp`.

2021-05-27 02:09 UTC, LinuxSuRen approved these changes
/lgtm

2021-05-27 05:31 UTC, benjaminhuo approved these changes
/lgtm

2021-05-27 06:26 UTC, JohnNiang commented
/unhold

2021-05-31 01:41 UTC, JohnNiang commented
/cc @pixiake

2021-06-01 03:30 UTC, pixiake commented
/approve

2021-06-01 03:30 UTC, merged