add enable kubeedge guide
kubesphere/ks-installer pull request #1502
Opened 2021-04-30 04:35 UTC by zhu733756

Signed-off-by: zhu733756 <talonzhu@yunify.com>

2021-04-30 04:36 UTC, zhu733756 commented
/cc @benjaminhuo @pixiake

2021-04-30 04:52 UTC, benjaminhuo requested changes

2021-04-30 04:52 UTC, benjaminhuo commented on README.md
> +> Note: If you enable kubeedge component, please add advertiseAddress and related ports for master node before you run or restart deployment ks-installer. [The related documents](https://github.com/k
Note: If you enable KubeEdge, please set `advertiseAddress`  as below and expose corresponding ports correctly before you run or restart ks-installer.  Please refer to [KubeEdge Guide](https://kubesphere.io/docs/pluggable-components/kubeedge/) for more details.

2021-04-30 04:52 UTC, benjaminhuo commented on README.md
> +        - xxxx
`- xxx.xxx.xxx.xxx`

2021-04-30 04:52 UTC, benjaminhuo commented on README_zh.md
> +> 如果激活了kubeedge组件，在运行或重启ks-installer之前，需要配置主节点外网访问地址`advertiseAddress`，暴露相应的访问端口，请参考[相应文档](https://github.com/kubesphere/website/blob/master/content/en/docs/pluggable-components/kubeedge.md)：
如果要启用 KubeEdge ，在运行或重启 ks-installer 之前，需要配置集群外网访问地址`advertiseAddress`，暴露相应的访问端口，更多内容请参考[KubeEdge 指南](https://kubesphere.io/docs/pluggable-components/kubeedge/)：

2021-04-30 08:30 UTC, zhu733756 commented on README_zh.md
> +> 如果激活了kubeedge组件，在运行或重启ks-installer之前，需要配置主节点外网访问地址`advertiseAddress`，暴露相应的访问端口，请参考[相应文档](https://github.com/kubesphere/website/blob/master/content/en/docs/pluggable-components/kubeedge.md)：
fixed

2021-04-30 08:30 UTC, zhu733756 commented on README.md
> +        - xxxx
fixed

2021-04-30 08:37 UTC, benjaminhuo commented
/lgtm

2021-04-30 08:38 UTC, benjaminhuo approved these changes

2021-05-06 01:54 UTC, pixiake commented
/approve

2021-05-06 01:55 UTC, merged