Provide more refined configuration of Devops agent
kubesphere/ks-installer pull request #1544
Opened 2021-06-15 16:38 UTC by JohnNiang

### What type of PR is this?
/area devops
/kind feature
### What this PR does / why we need it:
I provide three options for `devops.agent.config` configuration in ClusterConfiguration: default(or leave empty), high and custom, each representing a different limit level respectively, except for the custom option.

After doing this, 
- Users can configure different limit levels according to their own actual situation to improve the stability and efficiency of the system. 
- Once user has specified the custom option, any subsequent changes will not take effect.
- Even if uses upgrade from the old version, it will not have any impact.

**The main processing flow is as follow**:
![devops agent config update procedure](https://user-images.githubusercontent.com/16865714/122090498-643bd580-ce3a-11eb-8ce4-ed2107877947.png)
 
### Which issue(s) this PR fixes:

None

### Special notes for reviewers:
```
Test docker image: johnniang/ks-installer:agent-config-level
```

### Does this PR introduced a user-facing change?

```release-note

```
### Additional documentation, usage docs, etc.:

```docs

```

2021-06-16 10:10 UTC, LinuxSuRen requested changes
Before this PR get merged, a document is necessary. Please create an issue to describe it.

2021-06-16 10:10 UTC, LinuxSuRen commented on deploy/cluster-configuration.yaml
> +      config: default          # Available config level: default, high, custom
Acorronding to the context, `default`, `hight`, and `custom` is not a level. It sounds like a name of a configuration.

IMO `config` could be anything. We'd better give an explicit one. And Jenkins isn't always the only CI engine in the future. For example:

```
devops:
  jenkinsAgent:
    podResourceLimit: default
```

2021-06-16 10:10 UTC, LinuxSuRen commented on roles/ks-devops/jenkins/vars/jenkins_agent_limit_high.yaml
> +  concurrent: 20
Why is 20 here?

`20 x 4096Mi = 81920Mi = 80Gi`

`3000m * 20 = 60cores`

Are you sure that's what we want? IMO, it is a very big request for many users who wants to adapt KubeSphere DevOps in their team.

2021-06-16 15:55 UTC, JohnNiang commented on controller/schedule.sh
> +    str="successful!"
Thank you for pointing out, this change has noting to do with my feature. But I can confirm that the variable str is in code block scope, and the word `successsful` only appears once in current project. Finally, I agree with you, don't add irrelevant changes.

2021-06-16 15:57 UTC, JohnNiang commented
/hold

2021-06-16 16:00 UTC, JohnNiang commented on roles/ks-devops/jenkins/vars/jenkins_agent_limit_high.yaml
> +  concurrent: 20
Thank you for your correction. I'll change them to appropriate value.

2021-06-16 16:05 UTC, JohnNiang commented on roles/ks-devops/jenkins/vars/jenkins_agent_limit_high.yaml
> +  concurrent: 20
But I also want to say what really plays a decisive role is the limit of PodTemplate and hardware resources.

2021-06-16 16:06 UTC, JohnNiang commented on deploy/cluster-configuration.yaml
> +      config: default          # Available config level: default, high, custom
The name looks like good to me.

2021-06-17 00:52 UTC, LinuxSuRen commented on roles/ks-devops/jenkins/vars/jenkins_agent_limit_high.yaml
> +  concurrent: 20
> But I also want to say what really plays a decisive role is the limit of PodTemplate and hardware resources.

I didn't get your point here. Please explain it more.

2021-07-07 08:58 UTC, LinuxSuRen commented
I believe that this PR can close now.

2021-07-07 10:26 UTC, JohnNiang commented
Due to another implementation, we will close this issue later. Thanks for @LinuxSuRen 's mention.

/close

2021-07-07 10:26 UTC, closed without merging