Refactor/remove devops crd
kubesphere/ks-installer pull request #1559
Opened 2021-06-23 01:48 UTC by JohnNiang

2021-06-23 06:01 UTC, JohnNiang commented
/hold

2021-06-23 16:09 UTC, JohnNiang commented
/unhold

2021-06-24 07:03 UTC, JohnNiang commented
/cc @kubesphere/sig-devops

2021-06-24 07:03 UTC, JohnNiang commented
/cc @kubesphere/sig-installation

2021-06-24 07:11 UTC, LinuxSuRen requested changes
I don't think this PR is ready to review until the branch [remove-devops-ctrl](https://github.com/linuxsuren/kubesphere/tree/remove-devops-ctrl) was merged.

/block

2021-06-24 07:11 UTC, LinuxSuRen commented on deploy/kubesphere-installer.yaml
> +        image: johnniang/ks-installer:remove-devops-comp
Please don't use your personal image path.

2021-06-24 07:11 UTC, LinuxSuRen commented on roles/check-result/templates/welcome.j2
> +  -  Istio has already been upgraded to istio 1.6.10
I prefer do not change the number `1.` to `-1.

2021-06-24 07:21 UTC, JohnNiang commented on roles/check-result/templates/welcome.j2
> +  -  Istio has already been upgraded to istio 1.6.10
Mee too. I'll try to fix the possiable problem as follow:

```
1. xxx
2. yyy
4. zzz
```

2021-06-24 07:23 UTC, LinuxSuRen commented on roles/check-result/templates/welcome.j2
> +  -  Istio has already been upgraded to istio 1.6.10
> I prefer do not change the number 1. to -.

Sorry about this. I prefer to do not to change it, especially in this PR. If you want to improve it, please create a new PR against it.

2021-06-24 07:23 UTC, JohnNiang commented on deploy/kubesphere-installer.yaml
> +        image: johnniang/ks-installer:remove-devops-comp
Okay, I'll provide a permanent installation link for testing.

2021-06-24 07:25 UTC, LinuxSuRen commented
/hold

2021-06-24 07:41 UTC, JohnNiang commented
Due to [upstream branch](https://github.com/linuxsuren/kubesphere/tree/remove-devops-ctrl) hasn't been merged, I have to make this pr as draft again.

2021-07-19 06:54 UTC, JohnNiang commented
I'm going to close this issue until it is ready for test running and review.

2021-07-19 06:54 UTC, closed without merging