Issue-1614: make the resource of ks-apiserver and ks-controller-manager pods configurabable
kubesphere/ks-installer pull request #1615
Opened 2021-07-23 07:39 UTC by lshmouse

See: https://github.com/kubesphere/ks-installer/issues/1614

2021-07-23 07:46 UTC, LinuxSuRen requested changes
Thanks for your contribution. But I might found a potential compatible issue.

2021-07-23 07:46 UTC, LinuxSuRen commented on deploy/cluster-configuration.yaml
> +    apiserver:
This might be a breaking change. Before this PR, users can change the resource limit of `ks-apiserver` and `ks-controller-manager` by modifying the deployment. But `ks-installer` will overwrite the resource limit with this feature. In order to make it be easy to understand. Let me provide an example, let's assume this PR got merged.

* User A changes the resource limit of `ks-apisever` from 1024Mi to 2024Mi
* For some reason, the `ks-installer` restart, but User b provide the resource limit as 1024Mi in 
ClusterConfiguration

2021-07-26 12:34 UTC, lshmouse commented on deploy/cluster-configuration.yaml
> +    apiserver:
@LinuxSuRen In my options, this PR will not change the current behavior. In current implement,  the resource limit fo ks-apiserver and ks-controller-manager is configured in default values of ks-core helm chart(roles/ks-core/ks-core/files/ks-core/values.yaml). If user change the resource of the deployment and the cluster configuration is changed or the ks-installer is restarted, the resource change will also be rollbacked by the helm upgrade. 
      Maybe we should add some docs to remind users to be careful about changing the resource spec directly.

2021-07-28 07:04 UTC, pixiake commented
/lgtm
/approve

2021-07-28 07:04 UTC, merged