Add docker and crictl to offline-installation-tool.sh
kubesphere/ks-installer pull request #1843
Opened 2021-12-02 09:10 UTC by kinglong08

Solved this issue：https://github.com/kubesphere/ks-installer/blob/528c292b30efb2b3bf4a05d6349a150c559e99bc/scripts/offline-installation-tool.sh#L110

2021-12-02 11:57 UTC, kinglong08 commented
> /assign @24sama

2021-12-03 01:22 UTC, 24sama requested changes

2021-12-03 01:22 UTC, 24sama commented on scripts/offline-installation-tool.sh
> +     curl -L -o ${binariesDIR}/docker-${DOCKER_VERSION}.tgz https://mirrors.aliyun.com/docker-ce/linux/static/stable/x86_64/docker-${DOCKER_VERSION}.tgz
The `x86_64` should be the `${ARCH}`.

2021-12-03 01:22 UTC, 24sama commented on scripts/offline-installation-tool.sh
> +     curl -L -o ${binariesDIR}/docker-${DOCKER_VERSION}.tgz https://download.docker.com/linux/static/stable/x86_64/docker-${DOCKER_VERSION}.tgz
Here is also the x86_64 should be the ${ARCH}.

2021-12-03 01:36 UTC, 24sama commented
@kinglong08 
Thanks for your contribution!

2021-12-03 07:00 UTC, kinglong08 reviewed
x86_64   <=>  ${ARCH}

2021-12-03 07:00 UTC, 24sama approved these changes

2021-12-03 07:01 UTC, 24sama commented
/lgtm

2021-12-03 07:01 UTC, merged