upgrade prometheus stack
kubesphere/ks-installer pull request #1881
Opened 2022-01-05 09:02 UTC by junotx

Part of [#4426](https://github.com/kubesphere/kubesphere/issues/4575)  

Customize components for prometheus stack based on kube-prometheus release-0.10, and upgrade components as follows: 
- alertmanager to v0.23.0    
- grafana to 8.3.3   
- kube-state-metrics to v2.3.0   
- node-exporter to v1.3.1   
- prometheus to v2.32.1   
- prometheus-operator to v0.53.1   
- kube-rbac-proxy to v0.11.0   
- configmap-reload to v0.5.0   
- thanos to v0.23.2 

and remove the unused prometheus-adapter component. 

Incompatibilities in some metrics and rules due to components upgrades will be addressed in a separate pr later.

/assign @benjaminhuo @pixiake

2022-01-05 09:41 UTC, junotx commented on roles/ks-monitor/files/prometheus/alertmanager/alertmanager-serviceMonitor.yaml
> +  - interval: 30s
The scrape interval in all servicemonitors will be reverted to the previous 1m

2022-01-07 04:40 UTC, benjaminhuo requested changes

2022-01-10 05:37 UTC, junotx commented on roles/ks-monitor/files/prometheus/kube-state-metrics/kube-state-metrics-serviceMonitor.yaml
> +      regex: (pod|service|endpoint|namespace)
Here not sure what you mean. What is wrong with drop `pod` and `namespace` from target

2022-01-10 05:44 UTC, benjaminhuo commented on roles/ks-monitor/files/prometheus/kube-state-metrics/kube-state-metrics-serviceMonitor.yaml
> +      regex: (pod|service|endpoint|namespace)
Sorry, my bad.
Let me recheck this part.

2022-01-10 05:47 UTC, junotx commented on roles/ks-monitor/files/prometheus/prometheus-operator/prometheus-operator-serviceMonitor.yaml
> +      app.kubernetes.io/version: 0.53.1
Scraping istio metrics is now configured by servicemonitor and podmonitor. [Here](https://github.com/kubesphere/ks-installer/blob/master/roles/ks-istio/files/prometheus/prometheus-operator.yaml) is the configuration

2022-01-10 08:14 UTC, benjaminhuo commented on roles/ks-monitor/files/prometheus/kube-state-metrics/kube-state-metrics-serviceMonitor.yaml
> +      regex: (pod|service|endpoint|namespace)
@junotx If you take a look at the recording rules, the namespace and pod label are used actually.
https://github.com/kubesphere/kube-prometheus/blob/ks-v3.0/manifests/prometheus-rules.yaml#L499
You can search kube-state-metrics to find more in this file.

http://139.198.121.143:19090/graph?g0.expr=kube_configmap_info&g0.tab=1&g0.stacked=0&g0.range_input=1h this is an example

We may need to keep the pod and namespace label

2022-01-10 09:19 UTC, junotx commented on roles/ks-monitor/files/prometheus/kube-state-metrics/kube-state-metrics-serviceMonitor.yaml
> +      regex: (pod|service|endpoint|namespace)
The namespace and pod labels dropped here are in targets, not in metrics

2022-01-10 09:27 UTC, benjaminhuo commented on roles/ks-monitor/files/prometheus/kube-state-metrics/kube-state-metrics-serviceMonitor.yaml
> +      regex: (pod|service|endpoint|namespace)
If you take a look at the metrics scrapped, there is no service and endpoint label anymore and they will come back if you delete the `labeldrop`  section

![image](https://user-images.githubusercontent.com/18525465/148743400-41e9d04e-3bb8-41ec-a939-6a59ff78cb5a.png)

2022-01-10 09:29 UTC, junotx commented on roles/ks-monitor/files/prometheus/kube-state-metrics/kube-state-metrics-serviceMonitor.yaml
> +      regex: (pod|service|endpoint|namespace)
That's because service and endpoint labels are not in the metrics, otherwise they would be added.

2022-01-11 07:57 UTC, benjaminhuo commented
Update the quay or gcr image to dockerhub kubesphere image, then this PR is ready to go

2022-01-12 03:03 UTC, benjaminhuo commented
/lgtm

2022-01-12 03:04 UTC, benjaminhuo commented
/approve

2022-01-12 03:06 UTC, benjaminhuo commented
Some metrics name has been adjusted after upgrading node-exporter and kube-state-metrics

2022-01-14 09:35 UTC, benjaminhuo approved these changes

2022-01-14 09:37 UTC, merged