fix: add permission 'jenkins/labelsData' to pipline manage role
kubesphere/ks-installer pull request #1890
Opened 2022-01-17 06:54 UTC by 123liubao

Fix: https://github.com/kubesphere/ks-devops/issues/430

2022-01-17 06:55 UTC, 123liubao commented
/assign @24sama

2022-01-19 06:24 UTC, pixiake commented
/cc @LinuxSuRen @JohnNiang

2022-01-19 06:51 UTC, LinuxSuRen commented
> /cc @LinuxSuRen @JohnNiang

Thanks for ping us. But a better way is to ping the DevOps SIG team.

/cc @kubesphere/sig-devops

2022-01-19 06:56 UTC, LinuxSuRen requested changes
Thanks for your contribution.

In https://github.com/kubesphere/ks-devops/issues/430 , he met the permission issue with `artifact download` instead of Jenkins agent lable.

2022-01-19 06:56 UTC, LinuxSuRen commented on roles/ks-core/prepare/files/ks-init/role-templates.yaml
> +        - 'jenkins/labelsData'
This role already contains this resource permission.

```
iam.kubesphere.io/dependencies: '["role-template-view-pipelines", "role-template-manage-pipelineruns", "role-template-view-credentials"]'
```

See also https://github.com/kubesphere/ks-installer/blob/f860029d1d974698234d6aa249425e269af8e491/roles/ks-core/prepare/files/ks-init/role-templates.yaml#L3239

2022-01-19 07:06 UTC, LinuxSuRen commented
/area devops

2022-01-19 11:08 UTC, 123liubao commented on roles/ks-core/prepare/files/ks-init/role-templates.yaml
> +        - 'jenkins/labelsData'
OK, I would reproduce that issue first.

2022-01-20 07:32 UTC, 123liubao commented
@LinuxSuRen 
I have reproduced this issue, artifact download use the API 
`/kapis/devops.kubesphere.io/v1alpha2/jenkins/job/cly-devops7846x/job/test-pipeline/2/artifact/target/devops-sample-0.0.1-SNAPSHOT.jar` to download and meet the following error:
![image](https://user-images.githubusercontent.com/87936714/150290857-65509540-754d-4d15-9a3b-290ec47c355c.png)

according to the error info , user cannot get resource 'jenkins/cly-devops7846x'  , but `/job/cly-devops7846x/job/test-pipeline/2/artifact/target/devops-sample-0.0.1-SNAPSHOT.jar` is jenkins url , so maybe we can not only add permissions to roles, but also update the rules of the url parse.
![image](https://user-images.githubusercontent.com/87936714/150292594-aa8809df-c6ea-4ec8-9fc8-5eb8887cfdc8.png)

2022-01-20 08:12 UTC, LinuxSuRen commented
hi @123liubao , thanks for your deep research on this issue.

I have a new idea. IMO, the following API is pretty ugly. The most important reason is that it is kind of a proxy of the Jenkins API. It's not necessary to expose any Jenkins-related path here.

`/kapis/devops.kubesphere.io/v1alpha2/jenkins/job/cly-devops7846x/job/test-pipeline/2/artifact/target/devops-sample-0.0.1-SNAPSHOT.jar`

So, how about creating a new API for this. For instance:

`GET /kapis/devops.kubesphere.io/v1alpha2/pipelineruns/demo-artifact-tt85n/artifacts?filePath=xxx.log`

* pros
  * Easy to understand, easy to memory, shorter
  * Less to expose the backend tech
  * Have the same permission control pattern (`pipelineruns/artifacts`)
* cons
  * Extra work: both the backend and frontend

2022-01-20 08:52 UTC, 123liubao commented
> hi @123liubao , thanks for your deep research on this issue.
> 
> I have a new idea. IMO, the following API is pretty ugly. The most important reason is that it is kind of a proxy of the Jenkins API. It's not necessary to expose any Jenkins-related path here.
> 
> `/kapis/devops.kubesphere.io/v1alpha2/jenkins/job/cly-devops7846x/job/test-pipeline/2/artifact/target/devops-sample-0.0.1-SNAPSHOT.jar`
> 
> So, how about creating a new API for this. For instance:
> 
> `GET /kapis/devops.kubesphere.io/v1alpha2/pipelineruns/demo-artifact-tt85n/artifacts?filePath=xxx.log`
> 
> * pros
>   
>   * Easy to understand, easy to memory, shorter
>   * Less to expose the backend tech
>   * Have the same permission control pattern (`pipelineruns/artifacts`)
> * cons
>   
>   * Extra work: both the backend and frontend

Thank you for your suggestion, it is more reasonable to use this method to deal with the problem.

2022-01-20 09:22 UTC, LinuxSuRen commented
> Thank you for your suggestion, it is more reasonable to use this method to deal with the problem.

I have created the corresponding issues (both backend and frontend)
* https://github.com/kubesphere/ks-devops/issues/449
* https://github.com/kubesphere/console/issues/2920

I'm going to hold this PR due to contributors might need to take some time to do it. We can unhold it until it is ready.

/hold

2022-01-21 02:24 UTC, pixiake commented
> > /cc @LinuxSuRen @JohnNiang
> 
> Thanks for ping us. But a better way is to ping the DevOps SIG team.
> 
> /cc @kubesphere/sig-devops

OK, Got it

2022-04-19 01:38 UTC, LinuxSuRen commented
hi @123liubao , I have fixed this issue. Please see https://github.com/kubesphere/ks-installer/pull/1948/files#diff-2af0949adc1f3d7b0f6737b5e6e3d1c870142695e9663faa9ac8641ac5d1fb78R3447

So, I guess we can close this PR.
/close

2022-04-19 01:38 UTC, closed without merging