WIP: Add Argo CD installation support
kubesphere/ks-installer pull request #1925
Opened 2022-04-02 10:01 UTC by LinuxSuRen

2022-04-06 12:35 UTC, JohnNiang commented
/close

2022-04-06 12:35 UTC, JohnNiang commented
/reopen

2022-04-07 02:02 UTC, LinuxSuRen commented
/label tide/merge-method-squash

2022-04-07 03:35 UTC, JohnNiang requested changes

2022-04-07 03:35 UTC, JohnNiang commented on roles/ks-devops/tasks/main.yaml
> +     {{ bin_dir }}/kubectl get cc -n kubesphere-system ks-installer -o=jsonpath='{.spec.devops.argocd.namespace}' | echo -n argocd
`| echo -n argocd` will make the result always to `argocd`. Please see below:

```bash
$ kubectl get cc -n kubesphere-system ks-installer -o=jsonpath='{.spec.devops.argocd.namespace}'                 
my-argocd%                                                                                                                           
$ kubectl get cc -n kubesphere-system ks-installer -o=jsonpath='{.spec.devops.argocd.namespace}' | echo -n argocd
argocd%
```

2022-04-07 03:58 UTC, JohnNiang commented on roles/ks-devops/tasks/main.yaml
> +     {{ bin_dir }}/kubectl get cc -n kubesphere-system ks-installer -o=jsonpath='{.spec.devops.argocd.namespace}' | echo -n argocd
I suggest using 

```bash
echo -n ${$({{ bin_dir }}/kubectl get cc -n kubesphere-system ks-installer -o=jsonpath='{.spec.devops.argocd.namespace}'):-argocd}
```

instead.

2022-04-07 05:57 UTC, LinuxSuRen commented on roles/ks-devops/tasks/main.yaml
> +     {{ bin_dir }}/kubectl get cc -n kubesphere-system ks-installer -o=jsonpath='{.spec.devops.argocd.namespace}' | echo -n argocd
I got an unexpected result in bash:
```shell
[root@node1 ~]# echo -n ${$(kubectl get cc -n kubesphere-system ks-installer -o=jsonpath='{.spec.devops.argocd.namespace}'):-argocd}
-bash: ${$(kubectl get cc -n kubesphere-system ks-installer -o=jsonpath='{.spec.devops.argocd.namespace}'):-argocd}: bad substitution
```

2022-04-07 06:04 UTC, JohnNiang commented on roles/ks-devops/tasks/main.yaml
> +     {{ bin_dir }}/kubectl get cc -n kubesphere-system ks-installer -o=jsonpath='{.spec.devops.argocd.namespace}' | echo -n argocd
I got the same error in bash. You could split the command into two commands like this:

```bash
ns=$(kubectl get cc -n kubesphere-system ks-installer -o=jsonpath='{.spec.devops.argocd.namespace}')
echo ${ns:-argocd}
```

2022-04-07 07:13 UTC, LinuxSuRen commented on roles/ks-devops/tasks/main.yaml
> +     {{ bin_dir }}/kubectl get cc -n kubesphere-system ks-installer -o=jsonpath='{.spec.devops.argocd.namespace}' | echo -n argocd
Good catch! Fixed!

2022-04-07 07:43 UTC, JohnNiang requested changes

2022-04-07 07:43 UTC, JohnNiang commented on roles/ks-devops/tasks/main.yaml
>    shell: >
Please change `shell: >` to `shell: |` here. This way represents that the following content are multi line shell script instead of one line command.

2022-04-07 07:44 UTC, JohnNiang commented on roles/ks-devops/tasks/main.yaml
>    shell: >
Please refer to https://docs.ansible.com/ansible/latest/reference_appendices/YAMLSyntax.html

2022-04-07 07:55 UTC, JohnNiang approved these changes
/lgtm

2022-04-07 08:29 UTC, JohnNiang commented
/cc @kubesphere/sig-installation

2022-04-07 08:41 UTC, LinuxSuRen commented
/area devops

2022-04-07 14:19 UTC, JohnNiang reviewed
/kind feature
/cc @kubesphere/sig-installation

2022-04-07 23:48 UTC, pixiake commented
/approve

2022-04-07 23:48 UTC, merged