ks-installer integration with opensensearch
kubesphere/ks-installer pull request #2081
Opened 2022-08-22 07:41 UTC by wenchajun

Signed-off-by: chengdehao <dehaocheng@kubesphere.io>

2022-08-22 09:53 UTC, wenchajun commented
/cc @wanjunlei

2022-08-22 10:18 UTC, wanjunlei commented on roles/ks-auditing/templates/custom-output-opensearch-auditing.yaml.j2
> +    host: "{% if common.opensearch.externalOpensearchHost is defined and common.opensearch.externalOpensearchHost != "" %}{{ common.opensearch.externalOpensearchHost }}{% else %}opensearch-cluster-da
Why use the data service, not the master service?

2022-08-22 10:18 UTC, wanjunlei commented on roles/ks-istio/templates/jaeger-cr.yaml.j2
> +        server-urls: https://opensearch-cluster-data.kubesphere-logging-system.svc:9200
Why use the data service, not the master service?

2022-08-24 07:50 UTC, wanjunlei approved these changes

2022-08-25 12:57 UTC, wenchajun commented
/cc @benjaminhuo

2022-08-27 05:41 UTC, wenchajun commented
> /cc @benjaminhuo

FIXED

2022-08-29 01:58 UTC, benjaminhuo requested changes

2022-08-29 01:58 UTC, benjaminhuo commented on roles/common/templates/custom-values-opensearch-master.yaml.j2
> +  requests:
The master node will not consume so much resources, should be similar to https://github.com/kubesphere/charts/blob/KubeSphere/stable/elasticsearch/values.yaml#L107

2022-08-29 02:00 UTC, benjaminhuo commented on roles/common/templates/custom-values-opensearch-data.yaml.j2
> +    memory: {{ common.opensearch.data.resources.limits.memory | default("2048Mi") }}
We needn't set a memory limit here because the memory is controlled by `opensearchJavaOpts: "-Xmx1536M -Xms1536M"`

2022-08-29 02:01 UTC, benjaminhuo commented on roles/common/templates/custom-values-opensearch-master.yaml.j2
> +    memory: {{ common.opensearch.master.resources.limits.memory | default("1024Mi") }}
We needn't set a memory limit here because the memory is controlled by `opensearchJavaOpts: "-Xmx512M -Xms512M"`

2022-08-29 05:59 UTC, benjaminhuo commented
/lgtm
/approve

2022-08-29 06:00 UTC, merged

2022-08-30 02:39 UTC, benjaminhuo commented
we need to cherry-pick this PR to qkcp-installer/qkcp